apiVersion: apps/v1
kind: Deployment
metadata:
  name: minisized-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minisized-web
  template:
    metadata:
      labels:
        app: minisized-web
    spec:
      containers:
      - name: minisized-web
        image: pys0530/minisized-web:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
