apiVersion: v1
kind: Service
metadata:
  name: minisized-web-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: minisized-web
  type: NodePort
status:
  loadBalancer: {}
